import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'apps', 'web', 'public');

// Fail fast if /play runtime imports reference missing static modules.
{
  const check = spawnSync('node', [path.join(ROOT, 'scripts', 'validate-play-runtime-imports.mjs')], {
    stdio: 'inherit'
  });
  if (check.status !== 0) {
    process.exit(check.status ?? 1);
  }
}

function env(name, fallback = '') {
  const value = process.env[name];
  return (value == null ? fallback : String(value)).trim();
}

function mustUrl(label, value) {
  if (!value) return '';
  try {
    // eslint-disable-next-line no-new
    new URL(value);
    return value;
  } catch {
    console.warn(`[netlify-build] invalid URL for ${label}: ${value}`);
    return '';
  }
}

const webApiOrigin = mustUrl(
  'ARENA_WEB_API_ORIGIN',
  env('ARENA_WEB_API_ORIGIN', 'https://arena-web.fly.dev')
);
const serverOrigin = mustUrl(
  'ARENA_SERVER_ORIGIN',
  env('ARENA_SERVER_ORIGIN', 'https://arena-server-broken-haze-6531.fly.dev')
);
const runtimeOrigin = mustUrl(
  'ARENA_RUNTIME_ORIGIN',
  env('ARENA_RUNTIME_ORIGIN', 'https://arena-agent-runtime.fly.dev')
);

// Write runtime-config.js so browser code can discover current origins without hardcoding.
const runtimeConfig = {
  webApiOrigin,
  serverOrigin,
  runtimeOrigin,
  // Preferred in-browser paths (Netlify rewrite targets)
  apiBase: '/api',
  challengesBase: '/challenges',
  presenceBase: '/presence',
  runtimeBase: '/runtime',
  serverHealthPath: '/server/health',
  gameWsPath: '/ws'
};

await writeFile(
  path.join(PUBLIC_DIR, 'runtime-config.js'),
  `// Generated by scripts/netlify-build.mjs\nwindow.ARENA_CONFIG = ${JSON.stringify(runtimeConfig, null, 2)};\n`,
  'utf8'
);

// Generate _redirects from env so we don't have to commit stale backend hostnames.
const redirects = [
  '# Generated by scripts/netlify-build.mjs',
  '# API + realtime proxy (frontend hosted on Netlify; backend on Fly)',
  `/api/health   ${webApiOrigin}/health           200`,
  `/api/*        ${webApiOrigin}/api/:splat       200`,
  `/health       ${webApiOrigin}/health           200`,
  '',
  '# WebSocket + backend proxy',
  `/ws           ${serverOrigin}/ws                200`,
  `/server/health ${serverOrigin}/health           200`,
  `/presence*    ${serverOrigin}/presence:splat    200`,
  `/challenges/* ${serverOrigin}/challenges/:splat 200`,
  `/runtime/*    ${runtimeOrigin}/:splat           200`,
  `/assets/world/* ${webApiOrigin}/assets/world/:splat 200`,
  '',
  '# Pretty routes -> static HTML',
  '/welcome   /welcome.html   200',
  '/dashboard /dashboard.html 200',
  '/play      /play.html      200',
  '/viewer    /viewer.html    200',
  '/profile   /dashboard      302',
  '/agents    /admin          301',
  '/admin     /admin-chief.html    200',
  '/admin-markets-lab /admin-markets-lab.html 200',
  '/users     /users.html     200',
  ''
].join('\n');

await writeFile(path.join(PUBLIC_DIR, '_redirects'), redirects, 'utf8');

console.log('[netlify-build] wrote apps/web/public/runtime-config.js and apps/web/public/_redirects');
