import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'apps', 'web', 'public');

// Fail fast if /play runtime imports reference missing static modules.
{
  const check = spawnSync('node', [path.join(ROOT, 'scripts', 'validate-play-runtime-imports.mjs')], {
    stdio: 'inherit'
  });
  if (check.status !== 0) {
    process.exit(check.status ?? 1);
  }
}

function env(name, fallback = '') {
  const value = process.env[name];
  return (value == null ? fallback : String(value)).trim();
}

function mustUrl(label, value) {
  if (!value) return '';
  try {
    // eslint-disable-next-line no-new
    new URL(value);
    return value;
  } catch {
    console.warn(`[netlify-build] invalid URL for ${label}: ${value}`);
    return '';
  }
}

const webApiOrigin = mustUrl(
  'ARENA_WEB_API_ORIGIN',
  env('ARENA_WEB_API_ORIGIN', 'https://arena-web-api-fresh-02240816.fly.dev')
);
const serverOrigin = mustUrl(
  'ARENA_SERVER_ORIGIN',
  env('ARENA_SERVER_ORIGIN', 'https://arena-server-fresh-02240816.fly.dev')
);
const runtimeOrigin = mustUrl(
  'ARENA_RUNTIME_ORIGIN',
  env('ARENA_RUNTIME_ORIGIN', 'https://arena-runtime-fresh-02240816.fly.dev')
);

// Write runtime-config.js so browser code can discover current origins without hardcoding.
const runtimeConfig = {
  webApiOrigin,
  serverOrigin,
  runtimeOrigin,
  // Preferred in-browser paths (Netlify rewrite targets)
  apiBase: '/api',
  challengesBase: '/challenges',
  presenceBase: '/presence',
  runtimeBase: '/runtime',
  serverHealthPath: '/server/health',
  gameWsPath: '/ws'
};

await writeFile(
  path.join(PUBLIC_DIR, 'runtime-config.js'),
  `// Generated by scripts/netlify-build.mjs\nwindow.ARENA_CONFIG = ${JSON.stringify(runtimeConfig, null, 2)};\n`,
  'utf8'
);

// Cutover mode: hard redirect Netlify traffic to the Fly web app.
const redirects = [
  '# Generated by scripts/netlify-build.mjs',
  '/* https://arena-web.fly.dev/:splat 301!'
].join('\n');

await writeFile(path.join(PUBLIC_DIR, '_redirects'), redirects, 'utf8');

console.log('[netlify-build] wrote apps/web/public/runtime-config.js and apps/web/public/_redirects');
