import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'apps', 'web', 'public');

// Fail fast if /play runtime imports reference missing static modules.
{
  const check = spawnSync('node', [path.join(ROOT, 'scripts', 'validate-play-runtime-imports.mjs')], {
    stdio: 'inherit'
  });
  if (check.status !== 0) {
    process.exit(check.status ?? 1);
  }
}

function env(name, fallback = '') {
  const value = process.env[name];
  return (value == null ? fallback : String(value)).trim();
}

function mustUrl(label, value) {
  if (!value) return '';
  try {
    // eslint-disable-next-line no-new
    new URL(value);
    return value;
  } catch {
    console.warn(`[netlify-build] invalid URL for ${label}: ${value}`);
    return '';
  }
}

const backendOrigin = mustUrl(
  'ARENA_BACKEND_ORIGIN',
  env('ARENA_BACKEND_ORIGIN', env('ARENA_WEB_API_ORIGIN', 'https://arena-backend.peppera.workers.dev'))
);
const runtimeOrigin = mustUrl(
  'ARENA_RUNTIME_ORIGIN',
  env('ARENA_RUNTIME_ORIGIN', 'https://arena-backend.peppera.workers.dev')
);
const worldAssetBaseUrl = mustUrl(
  'PUBLIC_WORLD_ASSET_BASE_URL',
  env('PUBLIC_WORLD_ASSET_BASE_URL', 'https://pub-302820e514cd451baaf272a33bd70765.r2.dev')
);

// Build hash — stamped into every deploy so the game client can detect
// when it's running stale code after a Netlify/Fly update and prompt reload.
// Uses GITHUB_SHA in CI; falls back to a timestamp for local builds.
const buildHash = env('GITHUB_SHA', Date.now().toString(36)).slice(0, 12);

// Write runtime-config.js so browser code can discover current origins without hardcoding.
const runtimeConfig = {
  backendOrigin,
  runtimeOrigin: backendOrigin || runtimeOrigin,
  worldAssetBaseUrl,
  // Preferred in-browser paths (Netlify rewrite targets)
  apiBase: '/api',
  runtimeBase: '/runtime',
  // Build identity — client polls /api/health and compares buildHash;
  // if it changes, the game prompts "New version available — reload?"
  buildHash
};

await writeFile(
  path.join(PUBLIC_DIR, 'runtime-config.js'),
  `// Generated by scripts/netlify-build.mjs\nwindow.ARENA_CONFIG = ${JSON.stringify(runtimeConfig, null, 2)};\n`,
  'utf8'
);

// Generate _redirects from env so we don't have to commit stale backend hostnames.
const redirects = [
  '# Generated by scripts/netlify-build.mjs',
  '# HTTP-first backend proxy (frontend hosted on Netlify)',
  `/api/health   ${backendOrigin}/health           200`,
  `/api/game/stations/playable ${backendOrigin}/api/game/stations/playable 200`,
  `/api/game/stations/interact ${backendOrigin}/api/game/stations/interact 200`,
  `/api/*        ${backendOrigin}/api/:splat       200`,
  `/health       ${backendOrigin}/health           200`,
  `/runtime/*    ${backendOrigin}/runtime/:splat   200`,
  `/assets/world/* ${worldAssetBaseUrl}/assets/world/:splat 200`,
  '',
  '# Pretty routes -> static HTML',
  '/welcome   /welcome.html   200',
  '/dashboard /dashboard.html 200',
  '/play      /play.html      200',
  '/viewer    /viewer.html    200',
  '/profile   /dashboard      302',
  '/agents    /admin          301',
  '/admin     /admin-chief.html    200',
  '/admin/markets-lab /admin-markets-lab.html 200',
  '/admin-markets-lab /admin-markets-lab.html 200',
  '/users     /users.html     200',
  '/skill     /skill.html     200',
  ''
].join('\n');

await writeFile(path.join(PUBLIC_DIR, '_redirects'), redirects, 'utf8');

console.log('[netlify-build] wrote apps/web/public/runtime-config.js and apps/web/public/_redirects');
